### PR TITLE
Bump dependencies

### PR DESCRIPTION
**Pull request by optikfluffel**

### CODE REVIEW

**Comment by kbaird** [comment]
Thank you. These bumps would be very helpful at our company, too. I'll be very happy to see this merged.

:+1:

**Comment by optikfluffel** [comment]
@kbaird you could, until this is getting merged, do something along the lines of:

```elixir
defp deps do
  [
    {:exvcr, git: "https://github.com/optikfluffel/exvcr.git", branch: "bump-dependencies"}
  ]
end
```

**Comment by kbaird** [comment]
@optikfluffel I already forked it before discovering your PR, but thanks for the suggestion (and for making the PR).

**Comment by parroty** [comment]
Thanks and sorry being late to merge.

**Pull request merged**
